packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    name                = "ubuntu/images/*ubuntu-noble-24.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_description = "DevOpsDays Tel Aviv 2019 Zen and the art of multi-cloud maintenance"
  ami_name        = "DevOpsDaysTLV2019-Zen-${local.timestamp}"
  instance_type   = "t2.medium"
  source_ami      = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username    = "ubuntu"
  ssh_interface   = "public_ip"
  associate_public_ip_address = true
  subnet_filter {
    filters = {
      "tag:Name" = "devopsdays-public"
    }
    most_free = true
    random    = true
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo 'packer' | {{ .Vars }} sudo -E -S bash '{{ .Path }}'"
    script          = "base.sh"
  }

}
